services:
#Servicio API GATEWAY    
    gateway-api:
        image: desafio2/gateway-api:1.0
        build:
            context: ./APIGateway
            dockerfile: Dockerfile
            target: runtime
        ports:
            - "5000:5000"
        depends_on:
            - usuarios-api
#Servicio USUARIOS API
    usuarios-api:
        image: desafio2/usuarios-api:1.0
        build:
          context: ./UsuarioAPI
          dockerfile: Dockerfile
          target: runtime
        ports:
          - "7116:7116"
        depends_on:
           - cache
           - db
#Servicio Redis Cache
    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
          - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes: 
          - cache:/data
#Servicio SQL Server
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: always
        environment:
          - SA_PASSWORD="Admin123"
          - ACCEPT_EULA="Y"
        ports:
          - "1433:1433"
        volumes:
          - sqlserver-data:/var/mssql/data
volumes:
    sqlserver-data:
    cache:
